export default class User {
  constructor(
    public username?: string,
    email?: string,
    public password?: string,
    first_name?: string,
    last_name?: string,
    age?: number,
    address?: string,
    city?: string,
    country?: string,
    phone_number?: string,
    zip_code?: string,
    gender?: string,
    date_of_birt?: string,
    registration_date?: string,
    last_login?: string,
    subscription_status?: boolean,
    account_balance?: number,
    loyalty_points?: number,
    preferred_language?: string,
    newsletter_subscription?: boolean,
    public role?: string,
    public token?: string,
    public exptokendate?: Date,
    public managerUser?: string,
    public managerUserName?: string,
    public lstManagerUser?: string[]
  ) {}
}
